(function (root) {
  'use strict';
  root.SWS = root.SWS || {};

  const rows = [
    ['wetse-01', "If I'm James Dean, You're Audrey Hepburn", 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-02', 'The Bomb Dot Com V2.0', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-03', 'You Kill Me (In a Good Way)', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-04', 'Let Love Bleed Red', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-05', 'Captain Tyin Knots vs. Mr. Walkway (No Way)', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-06', "Don't Fall Asleep at the Helm", 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-07', 'With Ears to See, and Eyes to Hear', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-08', 'In Case of Emergency, Dial 411', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-09', 'The Left Side of Everywhere', 'With Ears to See and Eyes to Hear', 2010, 'studio'],
    ['wetse-10', 'Dance Party', 'With Ears to See and Eyes to Hear', 2010, 'studio'],

    ['lctt-01', 'Do It Now Remember It Later', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-02', "If You Can't Hang", "Let's Cheers to This", 2011, 'studio'],
    ['lctt-03', 'Who Are You Now', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-04', 'Four Corners and Two Sides', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-05', "A Trophy Father's Trophy Son", "Let's Cheers to This", 2011, 'studio'],
    ['lctt-06', 'Fire', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-07', 'Tally It Up: Settle the Score', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-08', "Your Nickel Ain't Worth My Dime", "Let's Cheers to This", 2011, 'studio'],
    ['lctt-09', 'Postcards and Polaroids', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-10', 'All My Heart', "Let's Cheers to This", 2011, 'studio'],
    ['lctt-11', "Let's Cheers to This", "Let's Cheers to This", 2011, 'studio'],

    ['movie-01', 'Scene One - James Dean & Audrey Hepburn', 'If You Were a Movie, This Would Be Your Soundtrack', 2012, 'acoustic'],
    ['movie-02', 'Scene Two - Roger Rabbit', 'If You Were a Movie, This Would Be Your Soundtrack', 2012, 'acoustic'],
    ['movie-03', 'Scene Three - Stomach Tied in Knots', 'If You Were a Movie, This Would Be Your Soundtrack', 2012, 'acoustic'],
    ['movie-04', "Scene Four - Don't You Ever Forget About Me", 'If You Were a Movie, This Would Be Your Soundtrack', 2012, 'acoustic'],
    ['movie-05', 'Scene Five - With Ears to See and Eyes to Hear', 'If You Were a Movie, This Would Be Your Soundtrack', 2012, 'acoustic'],
    ['single-dead-walker', 'Dead Walker Texas Ranger', 'Dead Walker Texas Ranger', 2012, 'single'],

    ['feel-01', 'Feel', 'Feel', 2013, 'studio'],
    ['feel-02', 'Here We Go', 'Feel', 2013, 'studio'],
    ['feel-03', 'Free Now', 'Feel', 2013, 'studio'],
    ['feel-04', 'Alone (feat. MGK)', 'Feel', 2013, 'studio'],
    ['feel-05', "I'll Take You There (feat. Shayley Bourget)", 'Feel', 2013, 'studio'],
    ['feel-06', 'The Best There Ever Was (feat. Fronz)', 'Feel', 2013, 'studio'],
    ['feel-07', 'Low', 'Feel', 2013, 'studio'],
    ['feel-08', 'Congratulations (feat. Matty Mullins)', 'Feel', 2013, 'studio'],
    ['feel-09', 'Déjà Vu', 'Feel', 2013, 'studio'],
    ['feel-10', "These Things I've Done", 'Feel', 2013, 'studio'],
    ['feel-11', 'Sorry', 'Feel', 2013, 'studio'],
    ['feel-12', 'Satellites', 'Feel', 2013, 'studio'],

    ['madness-01', 'Kick Me', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-02', 'Go Go Go', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-03', 'Gold', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-04', 'Save Me a Spark', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-05', 'Fly', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-06', 'The Strays', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-07', 'Left Alone', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-08', 'Better Off Dead', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-09', 'We Like It Loud', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-10', 'Heroine', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-11', 'November', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-12', 'Madness', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-13', "Don't Say Anything", 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-14', 'Parasites', 'Madness (Deluxe Edition)', 2015, 'studio'],
    ['madness-15', '2 Chord', 'Madness (Deluxe Edition)', 2015, 'studio'],

    ['lau-01', 'With Ears to See, and Eyes to Hear (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-02', "If I'm James Dean, You're Audrey Hepburn (Live)", 'Live and Unplugged', 2016, 'live'],
    ['lau-03', 'Gold (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-04', 'The Strays (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-05', 'Free Now (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-06', 'Who Are You Now (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-07', 'Go Go Go (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-08', 'Santeria (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-09', 'Save Me a Spark (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-10', 'Iris (Live)', 'Live and Unplugged', 2016, 'live'],
    ['lau-11', "If You Can't Hang (Live)", 'Live and Unplugged', 2016, 'live'],

    ['gossip-01', 'Gossip', 'Gossip', 2017, 'studio'],
    ['gossip-02', 'Empire to Ashes', 'Gossip', 2017, 'studio'],
    ['gossip-03', 'Legends', 'Gossip', 2017, 'studio'],
    ['gossip-04', 'Trouble', 'Gossip', 2017, 'studio'],
    ['gossip-05', 'One Man Army', 'Gossip', 2017, 'studio'],
    ['gossip-06', 'Cheers', 'Gossip', 2017, 'studio'],
    ['gossip-07', 'Closer', 'Gossip', 2017, 'studio'],
    ['gossip-08', 'Hole in My Heart', 'Gossip', 2017, 'studio'],
    ['gossip-09', 'I Need to Know', 'Gossip', 2017, 'studio'],
    ['gossip-10', 'The Chase', 'Gossip', 2017, 'studio'],
    ['gossip-11', 'War', 'Gossip', 2017, 'studio'],
    ['nyc-01', 'Legends (Acoustic; Live from NYC)', 'Live & Acoustic from NYC', 2017, 'live'],
    ['nyc-02', 'Gossip (Acoustic; Live from NYC)', 'Live & Acoustic from NYC', 2017, 'live'],
    ['nyc-03', 'One Man Army (Acoustic; Live from NYC)', 'Live & Acoustic from NYC', 2017, 'live'],
    ['single-christmas-road', 'Christmas on the Road', 'Christmas on the Road', 2017, 'single'],

    ['lost-01', 'Leave It All Behind', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-02', 'Never Enough (feat. Benji Madden)', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-03', 'How It Feels to Be Lost', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-04', 'Agree to Disagree', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-05', 'Ghost', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-06', 'Blood Lines', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-07', 'Break Me Down', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-08', 'Another Nightmare', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-09', 'P.S. Missing You', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-10', 'Medicine (Devil in My Head)', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-11', 'Dying to Believe', 'How It Feels to Be Lost (Deluxe)', 2019, 'studio'],
    ['lost-12', 'Talking to Myself', 'How It Feels to Be Lost (Deluxe)', 2020, 'studio'],
    ['lost-13', 'Leave It All Behind (Acoustic)', 'How It Feels to Be Lost (Deluxe)', 2020, 'acoustic'],
    ['lost-14', 'Agree to Disagree (Acoustic)', 'How It Feels to Be Lost (Deluxe)', 2020, 'acoustic'],
    ['lost-15', 'Ghost (Acoustic)', 'How It Feels to Be Lost (Deluxe)', 2020, 'acoustic'],

    ['collapse-01', 'Tyrants', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-02', 'Complete Collapse', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-03', 'Crosses (feat. Spencer Chamberlain of Underoath)', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-04', 'Family Tree', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-05', 'Let You Down (feat. Charlotte Sands)', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-06', 'Be Happy (feat. Royal & the Serpent)', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-07', 'Us (feat. Dorothy)', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-08', 'Ctrl + Alt + Del', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-09', 'Bloody Knuckles', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-10', 'Mr. Nice Guy', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-11', 'Apathetic', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-12', 'Grave', 'Complete Collapse (Deluxe)', 2022, 'studio'],
    ['collapse-13', 'Be Happy (Acoustic)', 'Complete Collapse (Deluxe)', 2023, 'acoustic'],
    ['collapse-14', 'Complete Collapse (Acoustic)', 'Complete Collapse (Deluxe)', 2023, 'acoustic'],
    ['collapse-15', "Don't Let the Party Die", 'Complete Collapse (Deluxe)', 2023, 'studio'],
    ['collapse-16', 'Let You Down (Acoustic)', 'Complete Collapse (Deluxe)', 2023, 'acoustic'],
    ['collapse-17', 'Us (Acoustic)', 'Complete Collapse (Deluxe)', 2023, 'acoustic'],

    ['audiotree-01', 'Tally It Up, Settle the Score (Audiotree Live Version)', 'Sleeping With Sirens on Audiotree Live', 2024, 'live'],
    ['audiotree-02', 'Do It Now Remember It Later (Audiotree Live Version)', 'Sleeping With Sirens on Audiotree Live', 2024, 'live'],
    ['audiotree-03', "A Trophy Father's Trophy Son (Audiotree Live Version)", 'Sleeping With Sirens on Audiotree Live', 2024, 'live'],
    ['audiotree-04', "If I'm James Dean, You're Audrey Hepburn (Audiotree Live Version)", 'Sleeping With Sirens on Audiotree Live', 2024, 'live'],
    ['audiotree-05', "If You Can't Hang (Audiotree Live Version)", 'Sleeping With Sirens on Audiotree Live', 2024, 'live'],

    ['ending-01', 'An Ending In Itself', 'An Ending In Itself', 2026, 'studio'],
    ['ending-02', 'Forever/Always', 'An Ending In Itself', 2026, 'studio'],
    ['ending-03', 'God In My Head', 'An Ending In Itself', 2026, 'studio'],
    ['ending-04', 'Need You Here', 'An Ending In Itself', 2026, 'studio'],
    ['ending-05', 'Left On Repeat', 'An Ending In Itself', 2026, 'studio'],
    ['ending-06', 'House Of Matches', 'An Ending In Itself', 2026, 'studio'],
    ['ending-07', 'Waiting For You', 'An Ending In Itself', 2026, 'studio'],
    ['ending-08', 'Paralyzed', 'An Ending In Itself', 2026, 'studio'],
    ['ending-09', 'Process', 'An Ending In Itself', 2026, 'studio'],
    ['ending-10', 'PTSD', 'An Ending In Itself', 2026, 'studio'],
    ['ending-11', 'Looking Back At Me', 'An Ending In Itself', 2026, 'studio'],
    ['ending-12', 'Storm Clouds', 'An Ending In Itself', 2026, 'studio'],
    ['apple-live-01', 'An Ending In Itself (Live at Apple Music Radio)', 'Live at Apple Music Radio', 2026, 'live'],
    ['apple-live-02', 'Iris (Live at Apple Music Radio)', 'Live at Apple Music Radio', 2026, 'live'],
    ['apple-live-03', 'With Ears to See and Eyes to Hear (Live at Apple Music Radio)', 'Live at Apple Music Radio', 2026, 'live'],
    ['big-gulps-01', "I'm Coming Home (Big Gulps)", "I'm Coming Home (Big Gulps)", 2026, 'acoustic'],
    ['big-gulps-02', "I'm Coming Home (Big Gulps) [Original Version]", "I'm Coming Home (Big Gulps)", 2026, 'single']
  ];

  root.SWS.catalog = rows.map(([id, title, album, year, type]) => ({ id, title, album, year, type }));
  root.SWS.sources = [
    'https://sirensmusic.co/',
    'https://music.apple.com/us/artist/sleeping-with-sirens/360773035',
    'https://musicbrainz.org/artist/3267d5a3-c72c-4c3b-bafe-ec8a569c0b74',
    'https://sumerianrecords.bandcamp.com/album/complete-collapse-deluxe'
  ];
})(typeof globalThis !== 'undefined' ? globalThis : window);
