// Development-only test. Uses an installed Playwright or PLAYWRIGHT_MODULE.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');

test('ranking persists; backups restore safely; mobile and keyboard controls work', async () => {
  assert.ok(fs.existsSync('index.html'), 'browser app is missing');
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '@playwright/test');
  const server = http.createServer((req, res) => {
    const pathname = new URL(req.url, 'http://localhost').pathname;
    const file = path.join(process.cwd(), pathname.endsWith('/') ? 'index.html' : path.basename(pathname));
    try {
      const content = fs.readFileSync(file);
      res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html');
      res.end(content);
    } catch { res.writeHead(404); res.end(); }
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const url = `http://127.0.0.1:${server.address().port}/sws_tierlist/`;
    await page.goto(url);
    await page.getByRole('button', { name: 'Add songs', exact: true }).click();
    await page.getByLabel('Song titles').fill('First track\nSecond track\nThird track');
    await page.getByLabel('Album or release').fill('Test album');
    await page.getByRole('button', { name: 'Save songs', exact: true }).click();
    const first = page.locator('#pool .song').filter({ hasText: 'First track' });
    const firstId = await first.getAttribute('data-song-id');
    await first.click();
    await page.locator('[data-tier="S"] .tier-label').click();
    await page.reload();
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 1);
    const saved = await page.evaluate(() => localStorage.getItem('sws-tierlist-v1'));
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export JSON' }).click();
    const download = await downloadPromise;
    const exported = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
    assert.deepEqual(exported.tiers.S, [firstId]);
    await page.locator('#pool .song').filter({ hasText: 'Second track' }).click();
    await page.locator('[data-tier="S"] .tier-label').click();
    const secondId = await page.locator('[data-tier="S"] .song').last().getAttribute('data-song-id');
    await page.locator('[data-tier="S"] .song').last().getByRole('button', { name: /Move earlier/ }).click();
    assert.equal(await page.locator('[data-tier="S"] .song').first().getAttribute('data-song-id'), secondId);
    const setFile = content => page.locator('#import-file').setInputFiles({ name: 'save.json', mimeType: 'application/json', buffer: Buffer.from(content) });
    page.once('dialog', dialog => dialog.dismiss());
    await setFile(saved);
    await page.waitForTimeout(100);
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 2);
    page.once('dialog', dialog => dialog.accept());
    await setFile(saved);
    await page.waitForTimeout(100);
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 1);
    await setFile('{"version":9}');
    await page.waitForTimeout(100);
    assert.match(await page.locator('#message').innerText(), /supported/i);
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 1);
    await page.locator('#pool .song').filter({ hasText: 'Second track' }).dragTo(page.locator('[data-tier="A"]'));
    assert.equal(await page.locator('[data-tier="A"] .song').count(), 1);
    await page.locator('[data-tier="A"] .song').first().dragTo(page.locator('[data-tier="S"] .song').first());
    assert.equal(await page.locator('[data-tier="S"] .song').first().getAttribute('data-song-id'), secondId);
    await page.locator('[data-tier="S"] .song').first().dragTo(page.locator('#library h2'));
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 1);
    await page.getByLabel('Search songs').fill('unlikely-song-name-xyz');
    assert.equal(await page.locator('#pool .song').count(), 0);
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 1);
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await page.getByLabel('Filter by album').selectOption('Test album');
    assert.equal(await page.locator('#pool .song').count(), 2);
    await page.getByRole('button', { name: 'Clear filters' }).click();
    await page.getByRole('button', { name: 'Add songs', exact: true }).click();
    await page.getByLabel('Song titles').fill('<img src=x onerror="window.injected=true">');
    await page.getByRole('button', { name: 'Save songs', exact: true }).click();
    await page.reload();
    assert.equal(await page.locator('.song').filter({ hasText: '<img src=x onerror=' }).count(), 1);
    assert.equal(await page.evaluate(() => window.injected), undefined);
    await page.setViewportSize({ width: 375, height: 812 });
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: 'tests/mobile.png', fullPage: false });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    const keyboardCard = page.locator('#pool .song').first();
    await keyboardCard.focus();
    await page.keyboard.press('Enter');
    await page.locator('[data-tier="S"]').focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('[data-tier="S"] .song').count(), 2);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: 'tests/desktop.png', fullPage: false });
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Reset rankings' }).click();
    assert.equal(await page.locator('#board .song').count(), 0);
    assert.equal(errors.length, 0, errors.join('\n'));
    const corrupt = '{bad-json';
    await page.evaluate(value => localStorage.setItem('sws-tierlist-v1', value), corrupt);
    await page.reload();
    await page.getByRole('button', { name: 'Add songs', exact: true }).click();
    await page.getByLabel('Song titles').fill('Recovery track');
    await page.getByRole('button', { name: 'Save songs', exact: true }).click();
    await page.locator('#pool .song').first().click();
    await page.locator('[data-tier="A"] .tier-label').click();
    assert.equal(await page.evaluate(() => localStorage.getItem('sws-tierlist-v1')), corrupt);
    assert.equal(await page.locator('.song select').count(), 0);
    const deniedPage = await browser.newPage();
    await deniedPage.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Denied'); } }));
    await deniedPage.goto(url);
    await deniedPage.getByRole('button', { name: 'Add songs', exact: true }).click();
    await deniedPage.getByLabel('Song titles').fill('Storage denied track');
    await deniedPage.getByRole('button', { name: 'Save songs', exact: true }).click();
    await deniedPage.locator('#pool .song').first().click();
    await deniedPage.locator('[data-tier="B"] .tier-label').click();
    const fallback = deniedPage.waitForEvent('download');
    await deniedPage.getByRole('button', { name: 'Export JSON' }).click();
    assert.ok(await fallback);
    const localPage = await browser.newPage();
    await localPage.goto(require('node:url').pathToFileURL(path.resolve('index.html')).href);
    assert.equal(await localPage.locator('.tier-row').count(), 6);
    await localPage.getByRole('button', { name: 'Add songs', exact: true }).click();
    await localPage.getByLabel('Song titles').fill('Local file track');
    await localPage.getByRole('button', { name: 'Save songs', exact: true }).click();
    await localPage.reload();
    assert.equal(await localPage.locator('#pool .song').filter({ hasText: 'Local file track' }).count(), 1);
  } finally {
    await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
});
